# Generated by Django 5.0.4 on 2024-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0004_answer_author_answer_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
