# Generated by Django 5.0.4 on 2024-05-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0005_question_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='imgs',
            field=models.ManyToManyField(related_name='voter_question', to='cmapp.img'),
        ),
    ]
