# Generated by Django 5.0.4 on 2024-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0006_img_question_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='imgs',
        ),
        migrations.AddField(
            model_name='question',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
