# Generated by Django 5.0.4 on 2024-05-23 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0009_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parenet_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmapp.comment'),
        ),
    ]
