# Generated by Django 5.0.4 on 2024-05-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0010_comment_parenet_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parenet_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='cmapp.comment'),
        ),
    ]
