# Generated by Django 5.0.4 on 2024-05-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0011_alter_comment_parenet_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parenet_comment',
            new_name='parent_comment',
        ),
    ]
