# Generated by Django 5.0.4 on 2024-05-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0013_comment_answer_alter_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmapp.answer'),
        ),
    ]
