# Generated by Django 5.0.4 on 2024-05-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0015_alter_comment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='C', max_length=50),
            preserve_default=False,
        ),
    ]
