# Generated by Django 5.0.4 on 2024-05-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0016_question_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
    ]
