# Generated by Django 5.0.4 on 2024-05-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0017_planguage_remove_question_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='planguage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmapp.planguage'),
            preserve_default=False,
        ),
    ]
