# Generated by Django 5.0.4 on 2024-05-30 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0018_question_planguage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('imgs', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_information', to=settings.AUTH_USER_MODEL)),
                ('planguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmapp.planguage')),
                ('voter', models.ManyToManyField(related_name='voter_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
