# Generated by Django 5.0.4 on 2024-05-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0019_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmapp.information'),
            preserve_default=False,
        ),
    ]
