# Generated by Django 5.0.4 on 2024-05-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0020_comment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmapp.information'),
        ),
    ]
